# Generated by Django 5.0.4 on 2024-04-24 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="autosalon",
            name="customers",
            field=models.ManyToManyField(
                blank=True,
                related_name="autosalons",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Customers of AutoSalon",
            ),
        ),
        migrations.AlterField(
            model_name="autosalon",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="autosalons",
                to="api.supplier",
                verbose_name="Suppliers of AutoSalon",
            ),
        ),
    ]
