# Generated by Django 5.0.4 on 2024-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_autosalon_customers_alter_autosalon_suppliers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="autosalons",
            field=models.ManyToManyField(
                blank=True,
                related_name="cars",
                to="api.autosalon",
                verbose_name="Autosalons with Car",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                related_name="cars_options",
                to="api.optioncar",
                verbose_name="Options of Car",
            ),
        ),
        migrations.AlterField(
            model_name="optioncar",
            name="cars",
            field=models.ManyToManyField(
                blank=True,
                related_name="options_car",
                to="api.car",
                verbose_name="Cars with Option",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="cars",
            field=models.ManyToManyField(
                blank=True,
                related_name="suppliers_of_car",
                to="api.car",
                verbose_name="Cars, which have Supplier",
            ),
        ),
    ]
