name: 'Code checks'
on:
  push:
  pull_request:

jobs:
  test-job:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'install python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: 'install deps'
      run: |
        python -m pip install pipenv
        pipenv install

    - name: 'run flake8'
      run: pipenv run flake8 --config .flake8

    - name: 'run mypy'
      run: cd autosalon && pipenv run mypy .


